<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Install_HSRival_Plugin</AssemblyName>
    <RootNamespace>HSRivalInstaller</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\HSRivalPlugin\bin\Release\net48\HSRivalPlugin.dll">
      <LogicalName>HSRivalPlugin.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\HSRivalScraper\bin\Release\net48\HSRivalScraper.exe">
      <LogicalName>HSRivalScraper.exe</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\HSRivalScraper\bin\Release\net48\Microsoft.Web.WebView2.Core.dll">
      <LogicalName>Microsoft.Web.WebView2.Core.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\HSRivalScraper\bin\Release\net48\Microsoft.Web.WebView2.WinForms.dll">
      <LogicalName>Microsoft.Web.WebView2.WinForms.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\HSRivalScraper\bin\Release\net48\Newtonsoft.Json.dll">
      <LogicalName>Newtonsoft.Json.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\HSRivalScraper\bin\Release\net48\WebView2Loader.dll">
      <LogicalName>WebView2Loader.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
